### ISSUE TITLE
Frontend Model Rework

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#243]
## A wrapper for bibliographic resouce

`TypedResourceView` makes the 157 properties of `BibliographicResource` accessible, by providing the usual `title`, `publicationYear`, `contributors` interface. It is dynamically prefixed with a type depending on the viewport (a specific type).

## Reuse of enums from the backend

Enums are now loaded from Anne's json file `enums.json`. Such that the enum values should always match. Note that in some cases, we still want to use typescript enums type-safety.

## Swagger-generated client library

We make use of the swagger generated client library, yet our very own `locdb.service.ts` still acts as a connector, making the different APIs available in a single interface. It also wraps every single `BibliographicResource` in a `TypedResourceView` for further processing.

- [x] Test it.

### Core 

- [x] `locdb.ts`
- [x] `locdb.services.ts`
- [x] Component `Suggestion`, but see Issue #242 
- [x] Component `AppWrapper`
- [x] Component `Commit` (even though unused)

### Logging

- [x] logging service

### Browse

- [x] Component `Browse`

### Resource related

- [x] Component `ResourceForm`
- [x] Component `ResourceCardGroup`

### Entry management

These ones are prepared to be capable of creating new entries, yet the resource or ToDo item needs to be passed ( see below)
- [x] Component `EntryCardGroup`
- [x] Component `EntryForm`
- [x] Component `EntryList`

### Mock data
- [x] Mock Resources
- [x] Mock ToDos

### Ingest

- [x] Touch `scan.component.ts`

### ToDo lists

Need Major rework (`ToDo` / `ToDoParts` vs `TypedResourceView`):

- [x] Component `ToDoList`
- [x] Component `ToDoDetail`
- [x] Component `ToDoLeaf`

Further testing of 
- [x] RefsInspector
- [x] Scaninspector

**Comment by lgalke** [comment]
Progress 4eddc93

**Comment by lgalke** [comment]
Progress 182d17dec5ac6e7713f9304be0659c9ac338287c

**Comment by lgalke** [comment]
Progress 0472b2d0f3c179e2762d1bfe53f2c00e06fa2bc9

**Comment by lgalke** [comment]
Progress 7e67fbad7f2ca45f7739b812686b42e3f8d43dc5

**Comment by lgalke** [comment]
Progress d2f1db6eb114125c7d8d420e1fe65b3c3447d2fd
